application:
  name: "v2rm"
  project: "v2rm"
  organization: "not robots fourm"
  storage:
  - name: "data"
    size: "1000"
    type: "sdd"
    mount_point: "/mnt/data"
routers:
- name: "main-data"
  custom_domains:
  - branch: "main"
    domain: "www.v2rm.com"
  routes:
  - application_name: "data"
    paths:
    - "/*"

