
application:
  name: "v2rm"
  project: "v2rm"
  organization: "not rebots forum"
  storage:
  - name: "images"
    size: "1000"
    type: "sdd"
    mount_point: "/mnt/images"
routers:
- name: "main-minisrv"
  custom_domains:
  - branch: "main"
    domain: "www.v2rm.com"
  routes:
  - application_name: "v2rm"
    paths:
    - "/*"



